# Generated by Django 5.2 on 2025-05-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
