# Generated by Django 5.1.7 on 2025-04-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_place',
            field=models.CharField(blank=True, help_text='Your favorite place (used for password recovery)', max_length=100, null=True),
        ),
    ]
